# Generated by Django 4.0.6 on 2023-02-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('+', 'Addition'), ('-', 'Subtraction'), ('*', 'Multiplication'), ('/', 'Division')], max_length=1)),
                ('operand1', models.IntegerField()),
                ('operand2', models.IntegerField()),
                ('answer', models.IntegerField()),
            ],
        ),
    ]
