# Generated by Django 4.0.6 on 2023-04-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='code',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
