# Generated by Django 4.0.6 on 2023-02-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('+', 'Addition'), ('-', 'Subtraction'), ('*', 'Multiplication'), ('/', 'Division')], max_length=1)),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('answer', models.IntegerField()),
                ('difficulty', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
