# Generated by Django 4.1.6 on 2023-02-24 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_departments_employees_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ClassId', models.AutoField(primary_key=True, serialize=False)),
                ('ClassName', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherId', models.AutoField(primary_key=True, serialize=False)),
                ('TeacherName', models.CharField(max_length=100)),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.teacher'),
        ),
    ]
