# Generated by Django 4.1.6 on 2023-02-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='ClassId',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='ProblemId',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='TeacherId',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
