# Generated by Django 4.1.6 on 2023-04-24 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_quizquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.class'),
        ),
    ]
